[DEFAULT]
debug = False
log_dir = /var/log/kolla/heat
log_file = $log_dir/heat-engine.log
heat_metadata_server_url = https://192.168.3.13:8000
heat_waitcondition_server_url = https://192.168.3.13:8000/v1/waitcondition
heat_stack_user_role = heat_stack_user
stack_domain_admin = heat_domain_admin
stack_domain_admin_password = l6nLrIKl2KrtbSFMWTQDgfbAoddqynUMr00lg2zC
stack_user_domain_name = heat_user_domain
num_engine_workers = 5
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
region_name_for_services = RegionOne
server_keystone_endpoint_type = public

[database]
connection = mysql+pymysql://heat:GlHijyjOK61LdbVigNifZ5ZTF8uJoa2sMCg7tpvD@192.168.3.14:3306/heat
connection_recycle_time = 10
max_pool_size = 1
max_retries = -1

[keystone_authtoken]
service_type = orchestration
www_authenticate_uri = https://192.168.3.13:5000
auth_url = https://192.168.3.14:5000
auth_type = password
project_domain_id = default
user_domain_id = default
project_name = service
username = heat
password = 3oFvri01afPagf7WETpCpHPg3QMXtyOWvdurj4o8
cafile = /etc/ssl/certs/ca-certificates.crt
region_name = RegionOne
memcache_security_strategy = ENCRYPT
memcache_secret_key = Y4uZ5N9ttJ0wrpY3HJzGOaNPIIIbaFSHtHYPVOmX
memcached_servers = 192.168.3.10:11211,192.168.3.11:11211,192.168.3.12:11211

[cache]
backend = oslo_cache.memcache_pool
enabled = true
memcache_servers = 192.168.3.10:11211,192.168.3.11:11211,192.168.3.12:11211

[trustee]
auth_url = https://192.168.3.14:5000
auth_type = password
user_domain_id = default
username = heat
password = 3oFvri01afPagf7WETpCpHPg3QMXtyOWvdurj4o8

[ec2authtoken]
auth_uri = https://192.168.3.14:5000

[oslo_messaging_notifications]
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
driver = noop

[oslo_messaging_rabbit]
use_queue_manager = true
heartbeat_in_pthread = False
rabbit_quorum_queue = true
rabbit_stream_fanout = true
rabbit_qos_prefetch_count = 1
rabbit_transient_quorum_queue = true

[clients]
endpoint_type = internalURL
ca_file = /etc/ssl/certs/ca-certificates.crt

[oslo_middleware]
enable_proxy_headers_parsing = true

[volumes]
backups_enabled = False

[oslo_concurrency]
lock_path = /var/lib/heat/tmp

