[DEFAULT]
debug = False
log_dir = /var/log/kolla/masakari

[api]
region = RegionOne
auth_url = https://192.168.3.14:5000
user_domain_id = default
project_name = service
project_domain_id = default
username = masakari
password = oouoaQ1uFljFcojLoXK0XYM9osbROt0nGZSas5mN
cafile = /etc/ssl/certs/ca-certificates.crt
api_interface = internal

[host]
restrict_to_remotes = true
disable_ipmi_check = true
pacemaker_node_type = cluster
corosync_multicast_interfaces = enp1s0
corosync_multicast_ports = 5405

[oslo_concurrency]
lock_path = /var/lib/masakari/tmp

