[DEFAULT]
debug = False
log_dir = /var/log/kolla/cinder
log_file = cinder-api.log
use_forwarded_for = true
use_stderr = false
my_ip = 192.168.3.10
volume_name_template = volume-%s
glance_api_servers = https://192.168.3.14:9292
glance_num_retries = 3
glance_ca_certificates_file = /etc/ssl/certs/ca-certificates.crt
api_paste_config = /etc/cinder/api-paste.ini
auth_strategy = keystone
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
enabled_backends = rbd-1
image_volume_cache_enabled = True
cinder_internal_tenant_project_id = 27a4f2b2fcd14673b0f9fc37179ca58e
cinder_internal_tenant_user_id = fa88e29e53d24569a45d5597f6de8536
scheduler_default_filters = InstanceLocalityFilter,AvailabilityZoneFilter,CapacityFilter,CapabilitiesFilter

[oslo_messaging_notifications]
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
driver = noop

[oslo_messaging_rabbit]
use_queue_manager = true
processname = cinder-api
heartbeat_in_pthread = True
rabbit_quorum_queue = true
rabbit_stream_fanout = true
rabbit_qos_prefetch_count = 1
rabbit_transient_quorum_queue = true

[oslo_middleware]
enable_proxy_headers_parsing = true

[nova]
interface = internal
auth_url = https://192.168.3.14:5000
auth_type = password
project_domain_id = default
user_domain_id = default
region_name = RegionOne
project_name = service
username = nova
password = 7PA6S2ZCsCZKelnIutYitrFL89f8MWGoLBPwexEb
cafile = /etc/ssl/certs/ca-certificates.crt

[database]
connection = mysql+pymysql://cinder:HX1VOvH4oAAIhGUeYjxQtBFpOdIee3zpHLfhw2sH@192.168.3.14:3306/cinder
connection_recycle_time = 10
max_pool_size = 1
max_retries = -1

[keystone_authtoken]
service_type = volume
service_token_roles_required = true
www_authenticate_uri = https://192.168.3.13:5000
auth_url = https://192.168.3.14:5000
auth_type = password
project_domain_id = default
user_domain_id = default
project_name = service
username = cinder
password = fIt2243Vq8X3xDOtx4s9mLxUySPp0eF4tSzOi5Gw
cafile = /etc/ssl/certs/ca-certificates.crt
region_name = RegionOne
memcache_security_strategy = ENCRYPT
memcache_secret_key = Y4uZ5N9ttJ0wrpY3HJzGOaNPIIIbaFSHtHYPVOmX
memcached_servers = 192.168.3.10:11211,192.168.3.11:11211,192.168.3.12:11211

[oslo_concurrency]
lock_path = /var/lib/cinder/tmp

[privsep_entrypoint]
helper_command = sudo cinder-rootwrap /etc/cinder/rootwrap.conf privsep-helper --config-file /etc/cinder/cinder.conf

[barbican]
auth_endpoint = https://192.168.3.14:5000
barbican_endpoint_type = internal
verify_ssl_path = /etc/ssl/certs/ca-certificates.crt

[coordination]

[rbd-1]
image_volume_cache_enabled = True

