[DEFAULT]
debug = False
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
log_file = /var/log/kolla/keystone/keystone.log
use_stderr = true

[oslo_middleware]
enable_proxy_headers_parsing = true

[database]
connection = mysql+pymysql://keystone:02UAjaApVWvxsopuWYkgOJHSQmlDgPMgwWowQLzI@192.168.3.14:3306/keystone?ssl_ca=/etc/ssl/certs/ca-certificates.crt
connection_recycle_time = 10
max_pool_size = 1
max_retries = -1

[token]
revoke_by_id = false
provider = fernet
expiration = 86400
allow_expired_window = 172800

[fernet_tokens]
max_active_keys = 3

[cache]
backend = oslo_cache.memcache_pool
enabled = true
memcache_servers = 192.168.3.10:11211,192.168.3.11:11211,192.168.3.12:11211

[oslo_messaging_notifications]
transport_url = rabbit://openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.10:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.11:5672,openstack:z6plYtFMLmc9hj6H6Fx9OuO0t2Ec1Lhc9Cunu448@192.168.3.12:5672//
driver = messagingv2
topics = barbican_notifications

[oslo_messaging_rabbit]
use_queue_manager = true
heartbeat_in_pthread = False
rabbit_quorum_queue = true
rabbit_stream_fanout = true
rabbit_qos_prefetch_count = 1
rabbit_transient_quorum_queue = true

